// NOTE: This file is generated by chored

import sbt._
import Keys._
import xerial.sbt.Sonatype.SonatypeKeys._
import xerial.sbt.Sonatype.sonatypeCentralHost

ThisBuild / sonatypeCredentialHost := sonatypeCentralHost

object ScalaProject {
	val hiddenProjectSettings = Seq(
		publish / skip := true,
	)

	def publicProjectSettings = Seq(
		publishTo := sonatypePublishToBundle.value,
		publishMavenStyle := true,
		Test / publishArtifact := false,
	)

	val scala3Version = "3.4.2"
}
